const $=id=>document.getElementById(id), R=6371000; let marks=[],active=0,pos=null,weather=null,lastFetch=0,line={pin:null,boat:null},deferredPrompt=null,simOn=false,simTimer=null;let map=L.map('map').setView([59.205,10.79],13), layers=L.layerGroup().addTo(map), boatMarker, routeLine, layLines=[], redRouteLine=null, pressTimer=null;L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OSM'}).addTo(map);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('install').hidden=false});$('install').onclick=()=>deferredPrompt?.prompt();
function rad(d){return d*Math.PI/180}function deg(r){return(r*180/Math.PI+360)%360}function norm(d){return(d%360+360)%360}function diff(a,b){return((a-b+540)%360)-180}function kt(ms){return(ms||0)*1.94384}function ms(kn){return kn/1.94384}function bearing(a,b,c,d){let p1=rad(a),p2=rad(c),dl=rad(d-b);return deg(Math.atan2(Math.sin(dl)*Math.cos(p2),Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl)))}function distance(a,b,c,d){let p1=rad(a),p2=rad(c),dp=rad(c-a),dl=rad(d-b),x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}function dest(lat,lon,brg,m){let δ=m/R,θ=rad(brg),φ1=rad(lat),λ1=rad(lon);let φ2=Math.asin(Math.sin(φ1)*Math.cos(δ)+Math.cos(φ1)*Math.sin(δ)*Math.cos(θ));let λ2=λ1+Math.atan2(Math.sin(θ)*Math.sin(δ)*Math.cos(φ1),Math.cos(δ)-Math.sin(φ1)*Math.sin(φ2));return{lat:deg(φ2),lon:deg(λ2)}}
function save(){localStorage.regattaV2=JSON.stringify({marks,active,line});render()}function load(){try{let s=JSON.parse(localStorage.regattaV2||'{}');marks=s.marks||[];active=s.active||0;line=s.line||line}catch{}render()}
function render(){layers.clearLayers();layLines.forEach(l=>l.remove());layLines=[];$('marks').innerHTML=marks.map((m,i)=>`<tr><td>${i===active?'▶ ':''}${i+1}</td><td>${m.name}</td><td>${m.type||'merke'}</td><td><button onclick="active=${i};save();update()" class="secondary">Velg</button></td></tr>`).join('');marks.forEach((m,i)=>L.marker([m.lat,m.lon]).addTo(layers).bindPopup(`${i+1}. ${m.name}`));if(routeLine)routeLine.remove();if(marks.length)routeLine=L.polyline(marks.map(m=>[m.lat,m.lon]),{color:'#20a4f3',weight:3}).addTo(map);if(line.pin&&line.boat){L.polyline([[line.pin.lat,line.pin.lon],[line.boat.lat,line.boat.lon]],{color:'#ffd166',weight:4}).addTo(layers);$('startline').textContent=`Startlinje satt. Pinne / bøye valgt på kart eller båtposisjon.`}if(marks.length)map.fitBounds(L.latLngBounds(marks.map(m=>[m.lat,m.lon])),{padding:[25,25]})}
async function fetchData(lat,lon){$('status').textContent='Henter vær/hav…';let wx=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=wind_speed_10m,wind_direction_10m,wind_gusts_10m&wind_speed_unit=ms&timezone=auto`;let sea=`https://marine-api.open-meteo.com/v1/marine?latitude=${lat}&longitude=${lon}&current=wave_height,wave_direction,wave_period,ocean_current_velocity,ocean_current_direction&timezone=auto`;let[w,m]=await Promise.all([fetch(wx).then(r=>r.json()),fetch(sea).then(r=>r.json())]);weather={wind:w.current,marine:m.current};$('status').textContent='Live'}
function simWeatherFallback(){if(weather)return;weather={wind:{wind_speed_10m:6,wind_direction_10m:225,wind_gusts_10m:8},marine:{wave_height:0.4,wave_direction:225,wave_period:3,ocean_current_velocity:0.25,ocean_current_direction:80}}}
function correction(brg){let m=weather?.marine||{};if(m.ocean_current_velocity==null||m.ocean_current_direction==null)return{corr:0,text:'ingen strømdata'};let side=m.ocean_current_velocity*Math.sin(rad(diff(m.ocean_current_direction,brg)));let corr=Math.max(-14,Math.min(14,deg(Math.atan2(side,3.0))));return{corr,text:`strøm ${m.ocean_current_velocity.toFixed(2)} m/s mot ${Math.round(m.ocean_current_direction)}°, komp ${corr.toFixed(0)}°`}}
function route(brg){let w=weather.wind,from=w.wind_direction_10m,to=norm(from+180),twa=Math.abs(diff(brg,from)),up=+$('upwind').value||43,down=+$('downwind').value||150,cur=correction(brg),mode,cands;if(twa<up){mode='KRYSS';cands=[norm(from+up+cur.corr),norm(from-up+cur.corr)]}else if(twa>down){mode='LENS/JIBB';let a=180-down;cands=[norm(to+a+cur.corr),norm(to-a+cur.corr)]}else{mode='DIREKTE/SLØR';cands=[norm(brg+cur.corr)]}cands=cands.map(c=>({course:c,err:Math.abs(diff(c,brg))})).sort((a,b)=>a.err-b.err);return{mode,best:cands[0].course,alt:cands[1]?.course,twa,cur}}
function boatIcon(){return L.divIcon({className:'boatIcon',html:`<div style="transform:rotate(${pos?.cog||0}deg)">⛵</div>`,iconSize:[30,30],iconAnchor:[15,15]})}
function update(){if(!pos||!weather)return;if(boatMarker){boatMarker.setLatLng([pos.lat,pos.lon]); boatMarker.setIcon(boatIcon())}else boatMarker=L.marker([pos.lat,pos.lon],{icon:boatIcon()}).addTo(map).bindPopup('Never 2 late');let w=weather.wind,m=weather.marine;$('wind').textContent=`${w.wind_speed_10m.toFixed(1)} m/s fra ${Math.round(w.wind_direction_10m)}°`;$('sea').textContent=`${m.wave_height??'–'} m / ${m.ocean_current_velocity??'–'} m/s`;if(active>=marks.length){$('leg').textContent='Ferdig';return}let t=marks[active],brg=bearing(pos.lat,pos.lon,t.lat,t.lon),d=distance(pos.lat,pos.lon,t.lat,t.lon);if(d<(+$('radius').value||60)&&active<marks.length-1){active++;save();return update()}let r=route(brg);$('leg').textContent=`${active+1}: ${t.name} (${Math.round(d)} m)`;$('course').textContent=`${Math.round(r.best)}°`;$('advice').textContent=`${r.mode}: styr ca. ${Math.round(r.best)}° mot ${t.name}${r.alt?`, alternativ ${Math.round(r.alt)}°`:''}.`;$('details').textContent=`Peiling ${Math.round(brg)}°, TWA ${Math.round(r.twa)}°, ${r.cur.text}. Fart ${kt(pos.sog).toFixed(1)} kn / kurs ${Math.round(pos.cog||0)}°.`;layLines.forEach(l=>l.remove());layLines=[];[r.best,r.alt].filter(Boolean).forEach(c=>{let p=dest(pos.lat,pos.lon,c,2500);layLines.push(L.polyline([[pos.lat,pos.lon],[p.lat,p.lon]],{color:'#ffd166',className:'layline'}).addTo(map))});drawRecommendedRoute(r,t);}

function drawRecommendedRoute(r,target){
  if(redRouteLine){redRouteLine.remove();redRouteLine=null}
  if(!pos||!target)return;
  const pts=[[pos.lat,pos.lon]];
  if(r.mode==='KRYSS'||r.mode==='LENS/JIBB'){
    const legLen=Math.max(500, Math.min(1800, distance(pos.lat,pos.lon,target.lat,target.lon)/2));
    const p1=dest(pos.lat,pos.lon,r.best,legLen);
    pts.push([p1.lat,p1.lon]);
    pts.push([target.lat,target.lon]);
  } else pts.push([target.lat,target.lon]);
  redRouteLine=L.polyline(pts,{color:'#ff1744',weight:5,opacity:.95}).addTo(map);
}

function addPointFromMap(latlng){const choice=prompt('Legg til punkt:\n1 = Start\n2 = Rundingsbøye\n3 = Mål\n4 = Startlinje pinne\n5 = Startlinje bøye','2');if(choice==='4'){line.pin={lat:latlng.lat,lon:latlng.lng};save();return}if(choice==='5'){line.boat={lat:latlng.lat,lon:latlng.lng};save();return}let type=choice==='1'?'start':choice==='3'?'mål':'runding';let name=choice==='1'?'Start':choice==='3'?'Mål':prompt('Navn på rundingsbøye:',`Bøye ${marks.length+1}`);if(!name)return;if(choice==='1'){marks.unshift({name,lat:latlng.lat,lon:latlng.lng,type});active=0}else marks.push({name,lat:latlng.lat,lon:latlng.lng,type});save()}
map.on('mousedown touchstart',e=>{clearTimeout(pressTimer);pressTimer=setTimeout(()=>addPointFromMap(e.latlng),650)});map.on('mouseup mouseout touchend touchcancel dragstart move',()=>clearTimeout(pressTimer));
$('start').onclick=()=>{simOn=false;clearInterval(simTimer);navigator.geolocation.watchPosition(async p=>{pos={lat:p.coords.latitude,lon:p.coords.longitude,sog:p.coords.speed||0,cog:p.coords.heading||0};map.setView([pos.lat,pos.lon],map.getZoom());if(Date.now()-lastFetch>300000){lastFetch=Date.now();try{await fetchData(pos.lat,pos.lon)}catch(e){$('status').textContent='Værfeil';$('advice').textContent='Klarte ikke hente vær/havdata: '+e.message}}update()},{enableHighAccuracy:true,maximumAge:1200,timeout:10000})};
$('sim').onclick=async()=>{simOn=!simOn;$('sim').textContent=simOn?'Stopp demo-sim':'Start demo-sim';clearInterval(simTimer);if(!simOn)return;pos=pos||{lat:59.2035,lon:10.7700,sog:ms(+$('simSpeed').value),cog:+$('simHeading').value};map.setView([pos.lat,pos.lon],14);try{await fetchData(pos.lat,pos.lon)}catch(e){simWeatherFallback();$('status').textContent='Demo fallback'}simTimer=setInterval(async()=>{pos.sog=ms(+$('simSpeed').value);pos.cog=+$('simHeading').value;let p=dest(pos.lat,pos.lon,pos.cog,pos.sog*1);pos.lat=p.lat;pos.lon=p.lon;if(Date.now()-lastFetch>300000){lastFetch=Date.now();try{await fetchData(pos.lat,pos.lon)}catch(e){}}update()},1000);update()};
$('useHere').onclick=()=>{if(!pos)return alert('Start GPS eller demo først');marks.push({name:`Merke ${marks.length+1}`,lat:pos.lat,lon:pos.lon,type:'merke'});save()};$('clear').onclick=()=>confirm('Tømme bane?')&&(marks=[],active=0,line={pin:null,boat:null},save());$('sample').onclick=()=>{marks=[{name:'Start',lat:59.2035,lon:10.7700,type:'start'},{name:'Toppmerke',lat:59.2245,lon:10.7920,type:'runding'},{name:'Offset',lat:59.2260,lon:10.7970,type:'runding'},{name:'Bunnmerke',lat:59.1980,lon:10.7620,type:'runding'},{name:'Mål',lat:59.2050,lon:10.7730,type:'mål'}];active=0;save()};$('setPin').onclick=()=>{if(!pos)return alert('Start GPS eller demo først');line.pin={lat:pos.lat,lon:pos.lon};save()};$('setBoat').onclick=()=>{if(!pos)return alert('Start GPS eller demo først');line.boat={lat:pos.lat,lon:pos.lon};save()};load();
